"""Open a branch + PR against the rdc-protocol-research repo with new mappings."""

import datetime
import json
import os
import subprocess
import tempfile
from pathlib import Path

from rdc_correlate.mappings import (
    diff_findings,
    inject_section,
    parse_parameters_md,
    render_tentative_section,
)


DEFAULT_RESEARCH_REPO = "andrewroydshayes/rdc-protocol-research"


def _run(cmd, cwd=None, check=True):
    return subprocess.run(
        cmd, cwd=cwd, check=check, text=True, capture_output=True
    )


def publish_findings(
    findings,
    research_repo=DEFAULT_RESEARCH_REPO,
    dry_run=False,
    local_clone_root=None,
):
    """Returns dict with {pr_url, branch, new_count, skipped_count}. Requires
    `gh` CLI authenticated with repo scope."""
    local_clone_root = local_clone_root or tempfile.mkdtemp(prefix="rdc-correlate-")
    clone_dir = os.path.join(local_clone_root, "rdc-protocol-research")

    if not os.path.isdir(clone_dir):
        _run(["git", "clone", "--quiet", f"https://github.com/{research_repo}.git", clone_dir])
    else:
        _run(["git", "fetch", "--quiet", "origin"], cwd=clone_dir)
        _run(["git", "checkout", "--quiet", "main"], cwd=clone_dir)
        _run(["git", "pull", "--quiet", "--ff-only", "origin", "main"], cwd=clone_dir)

    params_path = Path(clone_dir) / "PARAMETERS.md"
    existing_md = params_path.read_text()
    recorded = parse_parameters_md(existing_md)["all"]

    new_findings = diff_findings(findings, recorded)
    if not new_findings:
        return {"pr_url": None, "branch": None, "new_count": 0, "skipped_count": len(findings)}

    now = datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z"
    section = render_tentative_section(new_findings, now)
    updated = inject_section(existing_md, section)

    date_slug = now[:10]
    branch = f"discoveries/{date_slug}-{len(new_findings)}-new"

    if dry_run:
        diff_path = Path(local_clone_root) / "parameters.patch.md"
        diff_path.write_text(updated)
        findings_path = Path(local_clone_root) / "findings.json"
        findings_path.write_text(json.dumps(new_findings, indent=2))
        return {
            "pr_url": None,
            "branch": branch,
            "new_count": len(new_findings),
            "skipped_count": len(findings) - len(new_findings),
            "dry_run_dir": local_clone_root,
        }

    # Real push
    _run(["git", "checkout", "-B", branch], cwd=clone_dir)
    params_path.write_text(updated)
    _run(["git", "add", "PARAMETERS.md"], cwd=clone_dir)
    _run([
        "git", "-c", "user.email=rdc-correlate@users.noreply.github.com",
        "-c", "user.name=rdc-correlate bot",
        "commit", "-m",
        f"discoveries: {len(new_findings)} new TLV mappings from correlation run {now}",
    ], cwd=clone_dir)
    _run(["git", "push", "--quiet", "-u", "origin", branch, "--force"], cwd=clone_dir)

    body_lines = [
        f"Automated discoveries from a correlation run at {now}.",
        "",
        f"{len(new_findings)} new wire IDs correlate with Rehlko cloud fields above the confidence threshold.",
        "",
        "Generated by [rdc-correlate](https://github.com/andrewroydshayes/rdc-correlate). Review before merging.",
        "",
    ]
    pr = _run([
        "gh", "pr", "create",
        "--repo", research_repo,
        "--head", branch,
        "--base", "main",
        "--title", f"Add {len(new_findings)} machine-verified TLV mappings ({date_slug})",
        "--body", "\n".join(body_lines),
    ])
    return {
        "pr_url": pr.stdout.strip(),
        "branch": branch,
        "new_count": len(new_findings),
        "skipped_count": len(findings) - len(new_findings),
    }
